### PR TITLE
Address issue #111: pretty-print application/json schemas and examples.

### PR DESCRIPTION
**Pull request by balthorium**
Note, I didn't add pretty-printing for other mediatypes, but the prettyPrint() helper could be pretty easily extended to do that.  Also, I didn't do anything with the default item.handlebars, though it apparently contains a schema and example template as well.

### CODE REVIEW

**Comment by kevinrenskers** [comment]
I don't really see the point here, since you can also just properly indent the JSON within the RAML file?

**Comment by kevinrenskers** [comment]
Happy to hear the reasoning though :) However, I can't merge this with the added *.html and *.raml in the .gitignore. This messes with the example files.

**Comment by balthorium** [comment]
Sorry about the .gitignore, will fix.

I agree, if the RAML were being constructed by hand, one could pretty-print it there and it would render find.  In my case, though, the RAML is auto-generated by a utility that reads source-code and produces what you see there.  Even in the case of pre-pretty-printed JSON, though, I would think it's a nice feature that the html would auto-correct any errors or inconsistencies in the formatting.

**Comment by kevinrenskers** [comment]
Good point, didn't think about that use case. What tool do you use to auto generate RAML?

**Comment by kevinrenskers** [comment]
Sadly I have to close the PR and ask you to resubmit it to the develop branch. Please see https://github.com/kevinrenskers/raml2html/blob/master/CONTRIBUTING.md.

**Comment by balthorium** [comment]
Not a problem, will resubmit.  For auto-generating I'm currently using versly/wsdoc to generate RAML from JAX-RS annotations, Spring MVC annotations, javadocs, and reflection.  Basically putting together a deploy-time pipeline that gives us continuously updated REST API documentation.

**Pull request closed without merging**
