### PR TITLE
URL navigation on modal dialogs

### PR DESCRIPTION
**Pull request by zbycz**
Hi,

I missed a possibility to link directly to opened modal. So I implemented this feature. 
- link links directly to #{{../uniqueId}}_{{method}} 
- jquery observes hashchange event

The examples are also regerenerated. It can be seen here as well:
http://rawgit.com/zbycz/raml2html/patch-1/examples/example.html#_forecasts__geoposition__get

Thanks for merging or any comments :-)

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Looks great! Could you check the spacing and indentation of this though?

```
            $('.modal').on('hidden.bs.modal', function() {
              if(history && history.replaceState) { 
                history.replaceState({}, '', '#');
              }
            });
```

**Comment by zbycz** [comment]
Sure - fixed. Sorry, did this part in different editor :-)

**Comment by kevinrenskers** [comment]
No problem :) I'll test it tonight and merge & release then.

**Comment by phonyphonecall** [comment]
Hey zbycz thanks for roping me in on this one.

Manually typing in the URL seems to work well.

In the test given, I cannot seem to get the anchor to update as I work through the page. For example if I click on the GET /account/find to initiate the pop up info box, the URL should update accordingly with `#_account__find__get`. That way users can easily copy and paste the link to wherever they need it.

Obviously this is not a requirement, but seems to fit well into this feature's spec.

**Comment by zbycz** [comment]
@phonyphonecall) Oh yess, you're right! Thanks for noticing. I fixed the onclick only for the badge showing on the right side. And forgot that there is also this badge, when you expand the panel by clicking its url.

Now its fixed, see the same link above.

**Comment by phonyphonecall** [comment]
@zbycz thats exactly what I was thinking on #38! Looks good to me after quick manual testing. I'll leave the formal validation to the experts.

**Comment by kevinrenskers** [comment]
Great work guys, thanks for the testing as well! :)

**Comment by zbycz** [comment]
:+1:

**Comment by phonyphonecall** [comment]
:clap:

**Comment by kevinrenskers** [comment]
1.6.0 is released

**Pull request merged**
